---
title: "Flow maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
libs <- c("readr", "dplyr", "rnaturalearth", "rnaturalearthdata", "sf", "stringr", "gganimate")

installed_libs <- libs %in% rownames(installed.packages())
if (any(installed_libs == FALSE)) {
    install.packages(libs[!installed_libs])
}
invisible(lapply(libs, library, character.only = TRUE))
colours <- c("#00559D", "#AA7147")
```

## Import flow data

```{r load_data}
load_counts <- function(file) {
  types <- cols(col_character(), col_integer())
  counts <- read_csv(paste0("..\\..\\data\\tools\\flow_maps\\", file), col_types = types)
  counts
}

birth_counts <- load_counts("birth_counts.csv")
travel_counts <- load_counts("travel_counts.csv")
```

## Mapping

```{r cache = TRUE}
world_map_base_data_gen = function(country_name_adjust = c("Czech Republic" = "Czech Republic")) {
  data_out <- ne_countries(scale = "medium", returnclass = "sf") %>%
    filter(sovereignt != "Antarctica") %>%
    select(name_long, formal_en, pop_est, pop_rank, pop_year, gdp_md, gdp_year,
           economy, income_grp, region_un, subregion, region_wb, label_x,
           label_y, wikidataid, geometry)
  names(data_out)[1] <- "Country"

  data_out <- data_out %>%
  st_transform("ESRI:54030") %>%
  mutate(
    Country = str_replace_all(Country, country_name_adjust)
  )
  data_out
}

world_map_base_data <- world_map_base_data_gen(country_name_adjust = c(
  "Côte d'Ivoire" = "Ivory Coast",
  "The Gambia" = "Gambia",
  "Bosnia and Herzegovina" = "Bosnia Herzegovina",
  "Burkina Faso" = "Burkina",
  "Republic of the Congo" = "Congo",
  "Brunei Darussalam" = "Brunei",
  "Ireland" = "Ireland {Republic}"
))
```

```{r}
world_base_map = function(title_in = "Base map", caption_in = "Base caption") {
  world_base_map <- ggplot(world_map_base_data) + geom_sf(lwd = 0.3, colour = "white") +
    labs(title = element_blank(), x = element_blank(), y = element_blank()) +
    lims(y = c(-6000000,7800000)) + # TODO convert limits to degrees?
    theme_void(base_size = 24) +
    theme(
      plot.background = element_rect(fill = "white", colour = "white"),
      legend.title = element_text(size = 21, colour = colours[1]),
      legend.margin = margin(c(0,0,0,0)),
      legend.position.inside = c(0.2, 0.3),
      legend.key.size = unit(25, "points"),
      axis.text.y = element_blank(), axis.text.x = element_blank(),
      axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
      text = element_text(colour = colours[1])
    )
  world_base_map
}
```

# Generate matrix representing frequency of two countries mentioned

```{r}
get_country_coords_x <- function(country_name) {
  cent <- world_map_base_data %>% filter(Country == country_name) %>% st_geometry() %>% st_centroid()
  coords <- st_coordinates(cent)
  coords[1]
}
get_country_coords_y <- function(country_name) {
  cent <- world_map_base_data %>% filter(Country == country_name) %>% st_geometry() %>% st_centroid()
  coords <- st_coordinates(cent)
  coords[2]
}
```

```{r}
all_countries_raw <- tibble(
  Country = unique(bind_rows(birth_counts, travel_counts)$Country)
) %>% mutate(x = sapply(Country, get_country_coords_x),
             y = sapply(Country, get_country_coords_y))
all_countries <- all_countries_raw %>%
  mutate(x = ifelse(Country == "France", x + 450000, x), y = ifelse(Country == "France", y + 400000, y)) %>%
  mutate(x = ifelse(Country == "Chile", x - 150000, x), y = ifelse(Country == "Chile", y - 50000, y))
```

```{r, fig.width=14}
world_base_map() +
  geom_point(data = all_countries, aes(x=x, y=y), size = 0.5)
ggsave("map_centroids.png", dpi = 300)
```

### Appendix

```{r cache = TRUE}
# TODO this method is inefficient, refactor
travel_combs <- as.data.frame(t(combn(travel_counts$Country, 2)))
names(travel_combs) <- c("Country_1", "Country_2")
Country_1_x <- sapply(travel_combs$Country_1, get_country_coords_x)
Country_1_y <- sapply(travel_combs$Country_1, get_country_coords_y)
Country_2_x <- sapply(travel_combs$Country_2, get_country_coords_x)
Country_2_y <- sapply(travel_combs$Country_2, get_country_coords_y)
```

```{r}
travel_combs <- travel_combs %>% mutate(Country_1_x = Country_1_x, Country_1_y = Country_1_y,
                                        Country_2_x = Country_2_x, Country_2_y = Country_2_y)
travel_combs$Number <- sample(1:max(travel_counts$Number), nrow(travel_combs), replace = TRUE)
```

```{r, fig.width=14}
world_base_map() +
  #geom_label(data = world_map_base_data %>% filter(Country %in% all_countries$Country),aes(x=100000*label_x, y=100000*label_y, label=Country)) +
  #geom_label(data = all_countries, aes(x=x, y=y, label=Country), size = 1, alpha = 0.6, position = position_jitter(width = 50000, height = 300000)) +
  geom_point(data = all_countries, aes(x=x, y=y), size = 0.5)
ggsave("map_centroids.png", dpi = 300)
```

***

[Orbits!](../index.html)
